from typing import Dict

class Mol: ...

#    def HasSubstructMatch(str): ...

def MolFromTPLFile(fileName: str, sanitize: bool, skipFirstConf: bool) -> Mol: ...
def MolFromTPLBlock(fileBlock: str, sanitize: bool, skipFirstConf: bool) -> Mol: ...
def MolFromMolFile(
    molFileName: str, sanitize: bool, removeHs: bool, strictParsing: bool
) -> Mol: ...
def MolFromSmiles(smi: str, sanitize: bool, replacements: Dict[str, str]) -> Mol: ...

# def MolFromSmarts(smi: str, mergeHs: bool) -> Mol: ...
# def MolToSmiles(mol: Mol) -> str: ...
